import { format } from 'date-fns';

interface BirthdayCardInput { staffName: string; position?: string | null; birthdayDate?: string; message: string; photoUrl?: string | null; companyName?: string; }
const defaultCompanyName = import.meta.env.VITE_COMPANY_NAME || 'Mezzo House Limited';

async function urlToImage(url?: string | null): Promise<HTMLImageElement | null> { if (!url) return null; try { const response = await fetch(url); if (!response.ok) return null; const blob = await response.blob(); const objectUrl = URL.createObjectURL(blob); const image = new Image(); image.src = objectUrl; await image.decode(); URL.revokeObjectURL(objectUrl); return image; } catch { return null; } }
function drawCoverImage(ctx: CanvasRenderingContext2D, image: HTMLImageElement, x: number, y: number, w: number, h: number) { const ratio = Math.max(w / image.width, h / image.height); const sw = w / ratio; const sh = h / ratio; const sx = (image.width - sw) / 2; const sy = (image.height - sh) / 2; ctx.drawImage(image, sx, sy, sw, sh, x, y, w, h); }
function wrapText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, maxWidth: number, lineHeight: number, maxLines = 10, align: CanvasTextAlign = 'left') { const oldAlign = ctx.textAlign; ctx.textAlign = align; const words = text.split(/\s+/).filter(Boolean); let line = ''; let lines = 0; for (const word of words) { const testLine = line ? `${line} ${word}` : word; if (ctx.measureText(testLine).width > maxWidth && line) { ctx.fillText(line, x, y); y += lineHeight; line = word; lines += 1; if (lines >= maxLines) break; } else line = testLine; } if (line && lines < maxLines) ctx.fillText(line, x, y); ctx.textAlign = oldAlign; return y + lineHeight; }
function rectRound(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) { ctx.beginPath(); ctx.moveTo(x + r, y); ctx.lineTo(x + w - r, y); ctx.quadraticCurveTo(x + w, y, x + w, y + r); ctx.lineTo(x + w, y + h - r); ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h); ctx.lineTo(x + r, y + h); ctx.quadraticCurveTo(x, y + h, x, y + h - r); ctx.lineTo(x, y + r); ctx.quadraticCurveTo(x, y, x + r, y); ctx.closePath(); ctx.fill(); }
function ribbon(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, color: string, cut = 34) { ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + w, y); ctx.lineTo(x + w - cut, y + h / 2); ctx.lineTo(x + w, y + h); ctx.lineTo(x, y + h); ctx.closePath(); ctx.fillStyle = color; ctx.fill(); }
function balloon(ctx: CanvasRenderingContext2D, x: number, y: number, radius: number, color: string) { const g = ctx.createRadialGradient(x - radius / 2, y - radius / 2, 6, x, y, radius); g.addColorStop(0, '#ffffff'); g.addColorStop(0.2, color); g.addColorStop(1, color); ctx.fillStyle = g; ctx.beginPath(); ctx.ellipse(x, y, radius * 0.8, radius, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#c46b16'; ctx.beginPath(); ctx.moveTo(x - 6, y + radius - 3); ctx.lineTo(x + 6, y + radius - 3); ctx.lineTo(x, y + radius + 10); ctx.closePath(); ctx.fill(); }
function dateParts(date?: string) { const d = date ? new Date(date) : new Date(); const valid = Number.isNaN(d.getTime()) ? new Date() : d; return { day: format(valid, 'do'), month: format(valid, 'MMMM') }; }

export async function generateBirthdayCardImage(input: BirthdayCardInput): Promise<string> {
  const canvas = document.createElement('canvas'); canvas.width = 900; canvas.height = 900; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Could not create birthday card canvas.');
  const staffName = input.staffName || 'Staff Member'; const position = input.position || 'Mezzo Maths Tutor'; const companyName = input.companyName || defaultCompanyName; const { day, month } = dateParts(input.birthdayDate); const photo = await urlToImage(input.photoUrl);
  ctx.fillStyle = '#f9ecef'; ctx.fillRect(0, 0, 900, 900); ctx.fillStyle = '#90b7ee'; ctx.fillRect(0, 0, 455, 450); ctx.fillRect(455, 450, 445, 450); ctx.fillStyle = '#eeeeee'; rectRound(ctx, 58, 42, 784, 808, 20);
  ctx.fillStyle = '#0c1a67'; ctx.beginPath(); ctx.arc(125, 100, 45, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#fff'; ctx.font = 'bold 27px Georgia, serif'; ctx.fillText('Mezzo', 92, 98); ctx.font = 'bold 17px Georgia, serif'; ctx.fillText('MATHS', 96, 121);
  ctx.fillStyle = '#f28c18'; ctx.fillRect(765, 0, 66, 68); ctx.fillStyle = '#111'; ctx.textAlign = 'center'; ctx.font = '25px Georgia, serif'; ctx.fillText(day.replace('th', 'ᵗʰ').replace('st', 'ˢᵗ').replace('nd', 'ⁿᵈ').replace('rd', 'ʳᵈ'), 798, 30); ctx.font = '15px Arial, sans-serif'; ctx.fillText(month, 798, 52); ctx.textAlign = 'left';
  ctx.fillStyle = '#f28c18'; ctx.beginPath(); ctx.moveTo(190, 145); ctx.lineTo(520, 145); ctx.lineTo(496, 195); ctx.lineTo(164, 195); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#36a9e1'; ctx.beginPath(); ctx.moveTo(198, 153); ctx.lineTo(528, 153); ctx.lineTo(496, 203); ctx.lineTo(164, 203); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#111'; ctx.font = 'bold 28px Georgia, serif'; ctx.textAlign = 'center'; wrapText(ctx, staffName, 350, 183, 270, 30, 1, 'center'); ctx.textAlign = 'left';
  const bColors = ['#2fb2ea', '#f28c18', '#2fb2ea', '#f28c18', '#2fb2ea', '#f28c18', '#2fb2ea']; [[600,190],[650,155],[700,190],[580,250],[635,250],[690,250],[735,250]].forEach(([x, y], i) => balloon(ctx, x, y, 36, bColors[i]));
  ctx.fillStyle = '#fff'; ctx.fillRect(95, 265, 425, 420); ctx.fillStyle = '#f6fff8'; ctx.fillRect(122, 292, 370, 360); if (photo) drawCoverImage(ctx, photo, 122, 292, 370, 360); else { ctx.fillStyle = '#dfe7f3'; ctx.fillRect(122, 292, 370, 360); ctx.fillStyle = '#718096'; ctx.font = 'bold 28px Arial, sans-serif'; ctx.textAlign = 'center'; ctx.fillText('Staff Photo', 307, 480); ctx.textAlign = 'left'; }
  ctx.fillStyle = '#36a9e1'; ctx.beginPath(); ctx.moveTo(110, 742); ctx.lineTo(420, 742); ctx.lineTo(386, 798); ctx.lineTo(76, 798); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#f28c18'; ctx.beginPath(); ctx.moveTo(98, 760); ctx.lineTo(424, 760); ctx.lineTo(390, 814); ctx.lineTo(64, 814); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#111'; ctx.font = '22px Arial, sans-serif'; ctx.fillText(position, 125, 795);
  ribbon(ctx, 535, 330, 300, 54, '#f28c18', 34); ctx.fillStyle = '#fff'; ctx.font = 'bold 28px Arial, sans-serif'; ctx.fillText('We wish you a', 552, 366);
  ctx.fillStyle = '#2b170e'; ctx.font = '74px Georgia, serif'; ctx.fillText('HAPPY', 548, 465); ctx.font = '66px Georgia, serif'; ctx.fillText('BIRTHDAY', 548, 535);
  ctx.fillStyle = '#111'; ctx.font = '25px Arial, sans-serif'; const msg = input.message || 'Today marks a very special day in your life. We join you to celebrate this day and pray that the Lord will bless you and keep you in health, strength and prosperity. God bless you.'; wrapText(ctx, `“${msg}”`, 548, 585, 270, 31, 7);
  ctx.font = '21px Arial, sans-serif'; ctx.textAlign = 'center'; wrapText(ctx, `... by management of ${companyName}.`, 690, 820, 285, 26, 2, 'center'); ctx.textAlign = 'left';
  return canvas.toDataURL('image/jpeg', 0.82);
}

export function dataUrlToFile(dataUrl: string, filename: string) { const [meta, base64] = dataUrl.split(','); const mimeMatch = meta.match(/data:(.*?);/); const mime = mimeMatch?.[1] || 'image/jpeg'; const binary = atob(base64); const bytes = new Uint8Array(binary.length); for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i); return new File([bytes], filename, { type: mime }); }
