import { FormEvent, useEffect, useState } from 'react';
import { useAuth } from '../lib/auth';
import { generateAppointmentLetter } from '../lib/documents';
import { supabase } from '../lib/supabase';
import { AppointmentLetterRequest, Profile } from '../types';

export function AdminDocuments() {
  const { profile } = useAuth();
  const [staff, setStaff] = useState<Profile[]>([]);
  const [form, setForm] = useState({ staff_id: '', appointment_date: '', position: 'Mezzo Maths Tutor', monthly_salary: '' });
  const [message, setMessage] = useState('');
  async function load() { const { data } = await supabase.from('profiles').select('*').neq('status', 'left').order('full_name'); const rows = (data || []) as Profile[]; setStaff(rows); if (!form.staff_id && rows[0]) setForm((p) => ({ ...p, staff_id: rows[0].id, position: rows[0].position || 'Mezzo Maths Tutor', appointment_date: rows[0].date_employed || '' })); }
  useEffect(() => { load(); }, []);
  function selectStaff(id: string) { const person = staff.find((row) => row.id === id); setForm((p) => ({ ...p, staff_id: id, position: person?.position || p.position, appointment_date: person?.date_employed || p.appointment_date })); }
  async function generate(event: FormEvent) { event.preventDefault(); if (!profile) return; const person = staff.find((row) => row.id === form.staff_id); if (!person) return; const request: AppointmentLetterRequest = { id: 'admin-generated', staff_id: person.id, status: 'approved', requested_at: new Date().toISOString(), decided_by: profile.id, decided_at: new Date().toISOString(), appointment_date: form.appointment_date, position: form.position, monthly_salary: Number(form.monthly_salary), admin_notes: 'Generated by admin' }; const { error } = await supabase.from('appointment_letter_requests').insert({ staff_id: person.id, status: 'approved', decided_by: profile.id, decided_at: new Date().toISOString(), appointment_date: form.appointment_date, position: form.position, monthly_salary: Number(form.monthly_salary), admin_notes: 'Generated by admin' }); if (error) setMessage(error.message); else setMessage('Appointment letter record saved. PDF downloading now.'); generateAppointmentLetter(person, request); }
  if (profile?.role !== 'admin') return <div className="empty">This page is for admin only.</div>;
  return <section><div className="page-header"><div><h1>Admin Documents</h1><p>Generate staff appointment letters directly for new entrants.</p></div></div>{message && <div className="status info">{message}</div>}<form className="panel form-grid" onSubmit={generate}><label>Staff<select value={form.staff_id} onChange={(e) => selectStaff(e.target.value)}>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name || person.email}</option>)}</select></label><div className="grid two"><label>Effective Date<input type="date" value={form.appointment_date} onChange={(e) => setForm({ ...form, appointment_date: e.target.value })} required /></label><label>Position<input value={form.position} onChange={(e) => setForm({ ...form, position: e.target.value })} required /></label></div><label>Monthly Salary<input type="number" value={form.monthly_salary} onChange={(e) => setForm({ ...form, monthly_salary: e.target.value })} required /></label><button className="primary">Generate Appointment Letter PDF</button></form></section>;
}
