import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { useAuth } from '../lib/auth';
import { generateAppointmentLetter } from '../lib/documents';
import { supabase } from '../lib/supabase';
import { AppointmentLetterRequest, Profile } from '../types';

const positions = ['Office Staff', 'Tutor', 'Supervisor', 'Marketer', 'Administration'];

function safeName(name: string) {
  return name.replace(/[^a-z0-9.]+/gi, '-').toLowerCase();
}

export function AdminDocuments() {
  const { profile } = useAuth();
  const [staff, setStaff] = useState<Profile[]>([]);
  const [uploads, setUploads] = useState<any[]>([]);
  const [form, setForm] = useState({ staff_id: '', appointment_date: '', position: 'Tutor', monthly_salary: '' });
  const [uploadForm, setUploadForm] = useState({ staff_id: '', letter_date: '', notes: '' });
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);

  async function load() {
    const [{ data: staffData }, { data: uploadData }] = await Promise.all([
      supabase.from('profiles').select('*').neq('status', 'left').order('full_name'),
      supabase.from('appointment_letter_uploads').select('*, profiles(full_name,email,position)').order('created_at', { ascending: false }).limit(100),
    ]);
    const rows = (staffData || []) as Profile[];
    setStaff(rows);
    setUploads(uploadData || []);
    if (!form.staff_id && rows[0]) {
      setForm((p) => ({ ...p, staff_id: rows[0].id, position: rows[0].position || 'Tutor', appointment_date: rows[0].date_employed || '' }));
      setUploadForm((p) => ({ ...p, staff_id: rows[0].id, letter_date: rows[0].date_employed || '' }));
    }
  }

  useEffect(() => { load(); }, []);

  function selectStaff(id: string) {
    const person = staff.find((row) => row.id === id);
    setForm((p) => ({ ...p, staff_id: id, position: person?.position || p.position, appointment_date: person?.date_employed || p.appointment_date }));
  }

  function selectUploadStaff(id: string) {
    const person = staff.find((row) => row.id === id);
    setUploadForm((p) => ({ ...p, staff_id: id, letter_date: person?.date_employed || p.letter_date }));
  }

  function selectFile(event: ChangeEvent<HTMLInputElement>) {
    setFile(event.target.files?.[0] || null);
  }

  async function generate(event: FormEvent) {
    event.preventDefault();
    if (!profile) return;
    const person = staff.find((row) => row.id === form.staff_id);
    if (!person) return;
    const request: AppointmentLetterRequest = { id: 'admin-generated', staff_id: person.id, status: 'approved', requested_at: new Date().toISOString(), decided_by: profile.id, decided_at: new Date().toISOString(), appointment_date: form.appointment_date, position: form.position, monthly_salary: Number(form.monthly_salary), admin_notes: 'Generated by admin' };
    const { error } = await supabase.from('appointment_letter_requests').insert({ staff_id: person.id, status: 'approved', decided_by: profile.id, decided_at: new Date().toISOString(), appointment_date: form.appointment_date, position: form.position, monthly_salary: Number(form.monthly_salary), admin_notes: 'Generated by admin' });
    if (error) setMessage(error.message); else setMessage('Appointment letter record saved. PDF downloading now.');
    generateAppointmentLetter(person, request);
  }

  async function uploadAppointmentLetter(event: FormEvent) {
    event.preventDefault();
    if (!profile || !file) { setMessage('Please select an appointment letter file to upload.'); return; }
    if (!uploadForm.staff_id) { setMessage('Please select the staff member.'); return; }
    setBusy(true); setMessage('');
    try {
      const path = `${uploadForm.staff_id}/${Date.now()}-${safeName(file.name)}`;
      const { error: uploadError } = await supabase.storage.from('appointment-letters').upload(path, file, { upsert: false, contentType: file.type || 'application/pdf' });
      if (uploadError) throw uploadError;
      const { error } = await supabase.from('appointment_letter_uploads').insert({
        staff_id: uploadForm.staff_id,
        uploaded_by: profile.id,
        file_name: file.name,
        file_path: path,
        letter_date: uploadForm.letter_date || null,
        notes: uploadForm.notes.trim() || null,
      });
      if (error) throw error;
      setMessage('Appointment letter uploaded successfully. The staff member can download it from Letters & Payslip.');
      setFile(null);
      setUploadForm({ staff_id: uploadForm.staff_id, letter_date: uploadForm.letter_date, notes: '' });
      await load();
    } catch (error: any) {
      setMessage(error.message || 'Could not upload appointment letter.');
    } finally { setBusy(false); }
  }

  async function openUploadedLetter(path: string) {
    const { data, error } = await supabase.storage.from('appointment-letters').createSignedUrl(path, 3600);
    if (error) { setMessage(error.message); return; }
    window.open(data.signedUrl, '_blank', 'noopener,noreferrer');
  }

  if (profile?.role !== 'admin') return <div className="empty">This page is for admin only.</div>;

  return <section>
    <div className="page-header"><div><h1>Admin Documents</h1><p>Generate or upload staff appointment letters directly for new entrants.</p></div></div>
    {message && <div className="status info">{message}</div>}

    <div className="grid two">
      <form className="panel form-grid" onSubmit={generate}>
        <h2>Generate Appointment Letter PDF</h2>
        <label>Staff<select value={form.staff_id} onChange={(e) => selectStaff(e.target.value)}>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name || person.email}</option>)}</select></label>
        <div className="grid two"><label>Effective Date<input type="date" value={form.appointment_date} onChange={(e) => setForm({ ...form, appointment_date: e.target.value })} required /></label><label>Position<select value={form.position} onChange={(e) => setForm({ ...form, position: e.target.value })}>{positions.map((position) => <option key={position} value={position}>{position}</option>)}</select></label></div>
        <label>Monthly Salary<input type="number" value={form.monthly_salary} onChange={(e) => setForm({ ...form, monthly_salary: e.target.value })} required /></label>
        <button className="primary">Generate Appointment Letter PDF</button>
      </form>

      <form className="panel form-grid" onSubmit={uploadAppointmentLetter}>
        <h2>Upload Appointment Letter</h2>
        <p className="hint">Upload a signed or prepared appointment letter PDF/DOC/DOCX for a staff member.</p>
        <label>Staff<select value={uploadForm.staff_id} onChange={(e) => selectUploadStaff(e.target.value)}>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name || person.email}</option>)}</select></label>
        <label>Letter Date<input type="date" value={uploadForm.letter_date} onChange={(e) => setUploadForm({ ...uploadForm, letter_date: e.target.value })} /></label>
        <label>Appointment Letter File<input type="file" accept=".pdf,.doc,.docx,image/*" onChange={selectFile} required /></label>
        <label>Notes<textarea value={uploadForm.notes} onChange={(e) => setUploadForm({ ...uploadForm, notes: e.target.value })} placeholder="Optional note for this upload." /></label>
        <button className="primary" disabled={busy}>{busy ? 'Uploading...' : 'Upload Appointment Letter'}</button>
      </form>
    </div>

    <div className="panel">
      <h2>Uploaded Appointment Letters</h2>
      <div className="table-card"><table><thead><tr><th>Date</th><th>Staff</th><th>File</th><th>Letter Date</th><th>Notes</th><th>Action</th></tr></thead><tbody>{uploads.map((row) => <tr key={row.id}><td>{new Date(row.created_at).toLocaleDateString()}</td><td>{row.profiles?.full_name || row.profiles?.email || '-'}</td><td>{row.file_name}</td><td>{row.letter_date || '-'}</td><td>{row.notes || '-'}</td><td><button className="primary small-button" onClick={() => openUploadedLetter(row.file_path)}>Open / Download</button></td></tr>)}</tbody></table></div>
      {uploads.length === 0 && <div className="empty">No appointment letters uploaded yet.</div>}
    </div>
  </section>;
}
